### PR TITLE
Generate a plot with the average values for each dataset

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by embaldridge** [comment]
I thought something like this might be coming down the pipeline.

**Comment by ethanwhite** [comment]
It's not exactly what they do, but I think it's close enough for the moment.

**Comment by embaldridge** [comment]
I assume that is the default color ramp?  It's actually doing really well with the colorblindness checker, which I'm very happy about.  I'll have a pull request with a couple of tweaks ready probably shortly.

**Comment by ethanwhite** [comment]
Yep, I'm just letting Seaborn do it's thing.

**Pull request merged**
