### PR TITLE
Plot for #183

### PR DESCRIPTION
**Pull request by davharris**
Thoughts/suggestions/edits welcome

image

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks pretty good.

* We should probably show 3 or 4 examples that show an diversity of different datasets and relative likelihoods.
* I'm fine with the use of lines but I wonder if many folks will find bars more intuitive as representing a probability distribution.

**Comment by embaldridge** [comment]
Checked for colorblindness compatibility?

**Comment by rueuntal** [comment]
Thanks, Dave! Looks great. Do we want to log-transform the axe(i)s?

**Comment by davharris** [comment]
Thanks for the feedback!

@ethanwhite:
* More data sets should be straightforward.
* I agree the lines aren't as accurate, but I couldn't think of a way to do it with bars or points that would be visually interpretable.

@embaldridge:
* Good point.  I'll look up how to change the colors in matplotlib.

@rueuntal:
* I'm not sure I see an advantage to log-transforming x?
* Log-transforming y would make the differences between the lines easier to spot, but we'd have to figure out how to deal with the zeros. It might also make it harder for some readers to interpret.

**Comment by ethanwhite** [comment]
> I agree the lines aren't as accurate, but I couldn't think of a way to do it with bars or points that would be visually interpretable.

Fair enough. My naive initial thought was light gray bars underneath the lines, but if you've already looked at those options I'm totally fine with this version.

**Comment by rueuntal** [comment]
> I'm not sure I see an advantage to log-transforming x?
Log-transforming y would make the differences between the lines easier to spot, but we'd have to figure out how to deal with the zeros. It might also make it harder for some readers to interpret.

I was thinking that transforming x might be necessary if y was transformed and the high abundance / low frequency tail was highlighted, but I'm totally on board with the "keep it easy for interpretation" argument.

**Comment by davharris** [comment]
I've tried a few options and I'm not really happy with any of them.  Maybe we don't need this figure so much?

**Comment by ethanwhite** [comment]
I like the idea of showing some example distributions and fits. If you want to swing by today and chat through the possibilities I'd be happy to do so.

**Comment by davharris** [comment]
Sure.  I’m in the unconference room when you’re free.

**Comment by davharris** [comment]
Here's the improved version in b8fe076.  The numbers in the legend are log-likelihoods.

See also the "notes" I added:

```
# Notes:  I'm only showing 1:50 on the x axis because letting the axis go out to 114 would only show 4 more points
#          but would take twice as much space.
#         Zipf spends too much probability mass at both extremes and not enough in the middle, where most of the
#          values are. It gets essentially no weight.
#         NB and PLN fit best, but only by 2 LL points. This isn't enough to overcome the AICc penalty relative
#          to log-series, which is always at least 2

```

image

**Comment by embaldridge** [comment]
The new bars look slick.  The lines for the different distributions aren't showing up well under colorblindness simulation.

**Comment by ethanwhite** [comment]
I'm still neutral on this at the moment. I think this gets looked at intuitively as "the log-series/zipf over-estimate rare species", but in reality they probably only over estimate singletons and underestimate doubletons and so they might be in the right general ballpark overall.

We could delve into binning, which has it's own set of issues... I guess I'm leaning back towards @davharris's thought a couple of days ago that maybe the complexities of putting this figure together in such a way was to avoid it increasing confusion mean that we're just as well off without it so that readers interpretation focuses on the overall results.

Thoughts?

**Comment by rueuntal** [comment]
I'd lean slightly towards keeping this figure since it shows visually how the distributions differ in shape. But I'm not at all attached to it.

**Comment by davharris** [comment]
I'm not leaning one way or the other.

@ethanwhite: not sure I understand what you mean here:

> I think this gets looked at intuitively as "the log-series/zipf over-estimate rare species", but in reality they probably only over estimate singletons and underestimate doubletons and so they might be in the right general ballpark overall.

To my eye, it looks like it overestimates singletons and then starts underestimating almost immediately.  It's below the observed values for 2, 4, 5, 7, and 9 through 17. Is that different from what you were saying? Sorry if I'm being dense.

**Comment by ethanwhite** [comment]
@davharris - no, we're saying the same thing. I just suspect that less discerning eyes will just look at the singleton column. I'm not sure why this concerned me a couple of hours ago to be honest.

I'm happy to keep some of these figures, so if folks like this general version then I think adding 2 or 3 more examples from other datasets (in a 2x2 or 1x3) should put us in pretty good shape.

**Comment by davharris** [comment]
Cool. So my current to-do list for this issue is 

* find colorblind-friendly palette for matplotlib
* make 2-3 more versions of the figure

Am I missing anything?

**Comment by ethanwhite** [comment]
> find colorblind-friendly palette for matplotlib

You could also just hard code colors since it's only 4 lines. There's an example of this in block `[17]` of https://github.com/weecology/bbs-forecasting/blob/master/forecasting-bbs-R.ipynb and a link in that comment with more details.

**Comment by davharris** [comment]
New version as of 	7cb9aa6. Thoughts?


image

**Comment by rueuntal** [comment]
Thanks, Dave!

The turquoise and magenta look a bit faded on my screen. Do we want to use
deeper colors?

**Comment by davharris** [comment]
How's this color scheme? Color Brewer says it's colorblind-safe and it's darker than the last set

image
image
image

**Comment by ethanwhite** [comment]
These look good to me. @embaldridge if you want to check them again to make sure they work go for it and them merge if you're happy.

**Comment by ethanwhite** [comment]
Use "Poisson lognormal" instead of "Poisson-lognormal" for consistency with updated text.

**Comment by ethanwhite** [comment]
I think "zipf" should be capitalized.

**Comment by ethanwhite** [comment]
Also, can we add letter labels to the panels so that I can reference the sites in the text.

**Comment by davharris** [comment]
@ethanwhite That should do it.  Could you take the lead on resizing everything so it looks nice for publication? If matplotlib is like R, getting all the plot elements to be reasonable sizes and non-pixellated can take some experience.

**Comment by ethanwhite** [comment]
Will do. Thanks!

**Comment by ethanwhite** [comment]
Unfortunately it turns out I can't because 2 of the 3 plots produce PLN nan's on my machine :frowning:

**Comment by rueuntal** [comment]
Let me see if I can take a crack.

**Comment by rueuntal** [comment]
The figure is [here](https://github.com/weecology/sad-comparison/blob/master/Fig1.pdf). Does it look good to everyone?

**Comment by ethanwhite** [comment]
It looks great Xiao. The one thing I'd change is let's drop the dataset names and numbers and just label the subplots. I'll include more meaningful information on the sites in the text (e.g., Breeding Bird Survey Route 36 from New York).

**Comment by rueuntal** [comment]
You mean A, B, C instead of A: BBS site... ?

**Comment by ethanwhite** [comment]
Yep.

**Pull request merged**
