### PR TITLE
Fixes #185, some relatively minor editing.

### LINKED ISSUE #185: FIA and Gentry counts are reversed in Table 1
These needed to be flipped.

### PR DESCRIPTION
**Pull request by embaldridge**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks great! I just pinged @davharris to check in on the status of the final analysis steps.

**Comment by rueuntal** [comment]
Has the geometric been removed?

**Comment by ethanwhite** [comment]
Yeah, we're going to pull it, but I figured I'd just get it on a more general edit as we gear up to get this out the door.

**Comment by rueuntal** [comment]
I see. Thanks!

**Comment by davharris** [comment]
I'll see if I can find the problem in #191 today.

**Pull request merged**
