### PR TITLE
Update code to plot Figure 1.

### PR DESCRIPTION
**Pull request by rueuntal**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks Xiao!

**Comment by ethanwhite** [comment]
@rueuntal - sorry I missed this before, but could you also add the plot itself as `example_plots.png`. I can't regenerate it do to my issues with the `nan`'s. Thanks.

**Comment by rueuntal** [comment]
No problem. It's done.

**Comment by ethanwhite** [comment]
Thanks.

**Pull request merged**
