### PR TITLE
Remove zeros before analyzing abundance distributions

### LINKED ISSUE #124: Remove zeros from analysis of miscDB in chapter3
I was unaware that there were zeros in the miscDB, so these need to be removed in the chapter 3 analyses.

### PR DESCRIPTION
**Pull request by ethanwhite**
Some of the datasets in miscDB include zeros. This was not accounted
for in the Connolly et al. analysis. This change removes the zeros
on import.

Fixes #124.

### CODE REVIEW

**Comment by embaldridge** [comment]
Thanks for the catch.

**Comment by embaldridge** [comment]
The original data query (misc-data-query.py) should have only pulled abundances greater than zero, so this shouldn't make a difference, assuming that the query worked how I thought I wrote it.

**Comment by ethanwhite** [comment]
Yeah, I ended up starting from scratch pulling data since we needed information that wasn't necessary for the original project. As a result I didn't benefit from your knowledge of the data and missed something. Fortunately when I reran the results last night it didn't change anything qualitatively.

**Comment by embaldridge** [comment]
Ah, I see.  Glad that it didn't change the general pattern of the results.

Elita Baldridge
Ph.D. candidate
Utah State University
Department of Biology and the Ecology Center

**Pull request merged**
