### PR TITLE
add nbinom, modeling & graphing in R

### PR DESCRIPTION
**Pull request by davharris**
This code does the following:

1) Calculate log-likelihoods for the negative binomial with R, which seems to have been more reliable for that computation.

2) Fit a mixed model that summarizes the effect of S and N for each distribution's log-likelihood, as well as the overall differences between methods

3) Generates example figures that could help address #181 and #182 (see below)

Note that the code currently assumes BBS data only; it should be straightforward to update it to work across data sets, however.

What do you think?

image
image

### CODE REVIEW

**Comment by ethanwhite** [comment]
Code looks good from a first read through. @rueuntal do you want to give it a quick read as well.

@davharris - have you done the same kind of checks you did on the Python code to confirm that the negative binomial fits are working better yet?

Since these are replacing graphs that are for all datasets combined we should probably go ahead and have them use all of the datasets at once for a starting point. Let us know if there's data that you don't have access to that you need to make this happen.

I like the graphs in general. If we go this direction I think we need to remake Figure 3 in the same style.

**Comment by rueuntal** [comment]
All looks good. My vote goes to the violin plots as well.

**Comment by davharris** [comment]
@ethanwhite: I think Elita gave me access to a Dropbox folder with all the data files, but it might make sense to run it all on your machine as a single pipeline for reproducibility reasons.  I'll expand it to incorporate all the files on a given machine.

For the mixed model, I'm currently using 

`log_likelihood ~ S_center * distribution + N_center * distribution + (1|site)`

as my formula.  In English, it has 

* A main effect for S and N.  Both of which are centered for improved interpretability; so the "default" values of S and N are now the means, rather than zero.
* A main effect for Distribution (pln, negbin, etc)
* Interactions between S and Distribution
* Interaction between N and Distribution
* A random effect to soak up residual differences among sites.

I was thinking I'd add a random effect for data set as well, but I need to think a bit more about exactly which lme4 incantation I want to use because sites are nested within data sets. I also need to look into whether I'd get a better fit if N and/or S were log-transformed.

I should probably also make a model for AICc in addition to this log-likelihood one.

I have two questions for both @ethanwhite and @rueuntal:

1) Does this seem useful? I think that---if we presented it well---it could produce some insights into when one method is better than another. If you think it's worth pursuing, I could make graphs that showed the expected log-likelihoods for each method as a function of S and N.

2) Is there anything you'd like to see added or removed from the model? I might not be thinking of everything, but it might be worth adding a two-way interaction between N and S.  Depending on how we present the model (e.g. as a table of coefficients or graphically), it might be worthwhile to add nonlinearities to the model as well.  Or, if we think this is already too complicated, I could remove some of the interactions, but I'd lean against that decision.

**Comment by ethanwhite** [comment]
> it might make sense to run it all on your machine as a single pipeline for reproducibility reasons

Happy to.

> 1) Does this seem useful? I think that---if we presented it well---it could produce some insights into when one method is better than another. If you think it's worth pursuing, I could make graphs that showed the expected log-likelihoods for each method as a function of S and N.

I don't have any objection to including this. However, if we decide to go this route we need to accept that there is the potential for quite a bit of re-writing. The Methods and the Results won't be too bad, but depending on the outcome we could end up with a pretty substantial Discussion rewrite. So deciding to go this route represents a tradeoff where this takes longer to get out the door and we have less time to work on other things. The flip side is that I agree that this could possibly lead to some interesting and insgithful results. What are your feelings on this @embaldridge?

**Comment by embaldridge** [comment]
Feelings are coming via email.

**Comment by davharris** [comment]
All right, I have a version that should be basically done now (including plots for log-likelihood, relative likelihood, AICc and AICc weights), unless I have a bug.  I'll review and clean up the code soon, but any feedback would also be helpful.

**Comment by davharris** [comment]
Okay, I've added checks for numerical precision in commit 9675809. 

The **short version** is, on BBS and MCDB, we should always have at least 6 digits of precision to work with, and I think that will be enough but should still double-check. In the mean time, @ethanwhite: can you run this branch's code on the remaining data sets to confirm no warnings are thrown on the remaining data sets? Just add the other data set names to the `ids` vector near the start of the script.  Thanks!

**Long version:**

To recap, the precision problems were related to subtracting off the log-probability of the zero class to account for truncation.  If the zero class's probability was too close to 1, then we'd be subtracting away all of our significant digits and end up with big rounding errors. More information can be found at https://github.com/weecology/macroecotools/issues/40 although the parameterization is a little different.

The new commit currently throws a warning if p0's probability is ever within 1E-10 of 1.0, which should give us about six digits of precision (assuming we have about sixteen digits to begin with, which I think is correct).  On BBS, I do get some warnings if I require 8 digits of precision, but that's probably overkill.  I'll double-check that later today.

**Comment by davharris** [comment]
Okay, I've found at least a couple of cases where setting the threshold at 1E-10 instead of 1E-8 turns out to be fine. 

Below is one example where `1-p0` is 6.879972e-10, which is much less than 1E-8, and R seems to have found a real optimum rather than just getting trapped in the low-precision noise from weecology/macroecotools#40

I'm basically satisfied with the R code now.

```
# BBS site 17010
ab = c(36L, 1L, 2L, 4L, 1L, 7L, 6L, 24L, 1L, 1L, 27L, 2L, 56L, 1L, 
  27L, 93L, 1L, 25L, 2L, 5L, 51L, 10L, 1L, 33L, 4L, 1L, 3L, 1L, 
  2L, 6L, 12L, 2L, 1L, 6L, 2L, 11L, 3L, 5L, 3L)

opt = list()
opt$par = c(-22.4546262607217, -18.5893290206489)

x = seq(-.1, .1, length = 100)


nb_nll = function(x, log_size, log_mu) {
  size = exp(log_size)
  mu = exp(log_mu)
  
  # Consider using log==TRUE and lower.tail==FALSE here, as opposed to
  # log(1-p0) below
  p0 = dnbinom(0, size = size, mu = mu, log = FALSE)
  
  full_ll = dnbinom(x, size = size, mu = mu, log = TRUE)
  
  -sum(full_ll - log(1 - p0))
}


plot(opt$par[1] + x, sapply(x, function(x){nb_nll(ab, opt$par[1] + x, opt$par[2])}),
     ylab = "negative log-likelihood", xlab = "log size", type = "l")
abline(v = opt$par[1])

plot(opt$par[2] + x, sapply(x, function(x){nb_nll(ab, opt$par[1], opt$par[2] + x)}),
     ylab = "negative log-likelihood", xlab = "log mu", type = "l")
abline(v = opt$par[2])
```

**Comment by ethanwhite** [comment]
The current code triggers the stop in `stopifnot(all(sites == results$site))` for CBC and NABA.

Removing those two datasets results in 41 warnings and then an error with:

```
Error in coord_cartesian(ylim = c(0, 1), expand = FALSE) : 
  unused argument (expand = FALSE)
```

**Comment by ethanwhite** [comment]
And here are the warnings:

```
> warnings()
Warning messages:
1: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 13021000013
2: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 14065000002
3: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 14093000065
4: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 15127000081
5: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 15133000107
6: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 53053000070
7: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 53059000048
8: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 55089000007
9: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 131029000120
10: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 133145000055
11: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 133169000038
12: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 134097000007
13: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 134157000074
14: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 135187000014
15: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 135241000026
16: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 182109010229
17: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 213051000005
18: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 213109000001
19: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 215093000003
20: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 215207000007
21: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 216003000021
22: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 264159020248
23: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 291149020168
24: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 291203020156
25: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 295099020202
26: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 363035006767
27: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 372127000021
28: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 420043001169
29: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 452025000095
30: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 453091000083
31: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 471023000017
32: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 472085000049
33: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 472099000054
34: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 474013000055
35: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 475123000097
36: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 481339000045
37: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 515169000074
38: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 542007001730
39: In FUN(X[[i]], ...) : p0 is too close to 1 infia site 544013002453
40: In FUN(X[[i]], ...) : p0 is too close to 1 ingentry site 35
41: In FUN(X[[i]], ...) : p0 is too close to 1 ingentry site 143
```

**Comment by davharris** [comment]
Ugh. So the first set of errors means that R and Python aren't always looking at the same site IDs. I'll check tomorrow if it's about how the IDs are encoded or if there's a more substantive problem. I'll also look into whether the "too close to 1" warnings indicate real problems. I suspect that they do, because I think the coord_cartesian error could mean that there are infinities. 

Bleh.

Dave

**Comment by davharris** [comment]
oh, I reread the coord_cartesian error; looks like we're just using different versions of ggplot2.  I'll make sure that whatever I have is up to date with the most recent version.

**Comment by davharris** [comment]
@ethanwhite could I get a copy of the `*_likelihood_results.csv` files from your most recent run of the Python code?

**Comment by ethanwhite** [comment]
[likelihood_results.zip](https://github.com/weecology/sad-comparison/files/199730/likelihood_results.zip)

They are also in the dropbox folder.

I'm not 100% sure what version of Python these were run on, but I grepped them and didn't seen any `nan` or `inf` so it's probably the right run. Let me know if you need me to rerun them now.

**Comment by davharris** [comment]
Thanks Ethan!

* Looks like FIA site 363035006767's rounding error is really bad in R. I'll need to see how many more sites have that sort of problem before proceeding.

* The two gentry sites are basically fine. The numerical precision for site 143 is a little on the low side, but not terrible. In both cases, the optimizer seems to have found a real optimum.

* Looks like the CBC and NABA problems are related to how I'm handling factors.  I'll look into this.

* Looks like the `Error in coord_cartesian` will go away if you update ggplot2 from CRAN.

**Comment by davharris** [comment]
Okay, @ethanwhite, this should now work once you update ggplot2, with the caveat that I'm finding multiple optima on some of the truncated negative binomial likelihoods.

Fortunately, I ***think*** that the multiple optima are basically numerical artifacts that arose from a combination of a very flat likelihood ridge and rounding errors, and we can basically ignore them.

For example, FIA site 15127000081 seems to have multiple optima (i.e. the BFGS optimizer finds one optimum and Nelder-Mead finds another).  These optima are very far apart in terms of the parameter estimates, but have basically equivalent likelihoods (-11.28339 versus -11.28281) because they sit on the same flat likelihood ridge.  So we might as well pick the optimum with lower rounding error.  On my machine, I never encounter a situation where both BFGS and Nelder-Mead find an optimum that's in the rounding error danger zone, so trying one when the other fails solves the problem.

Let me know if you run into any more trouble or if you think there's anything problematic about this.

**Comment by ethanwhite** [comment]
Great. Everything runs now.

Here are the current warnings:

```
> warnings()
Warning messages:
1: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
2: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
3: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
4: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
5: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
6: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
7: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
8: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
9: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
10: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
11: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
12: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
13: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
14: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
15: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
16: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
17: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
18: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
19: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
20: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
21: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
22: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
23: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
24: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
25: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
26: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
27: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
28: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
29: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
30: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
31: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
32: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
33: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
34: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
35: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
36: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
37: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
38: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
39: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
40: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
41: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
42: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
43: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
44: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
45: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
46: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
47: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
48: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
49: In dnbinom(x, size = size, mu = mu, log = TRUE) : NaNs produced
50: In dnbinom(0, size = size, mu = mu, log = FALSE) : NaNs produced
```

If these look OK to you then we can go ahead and merge, just wanted to make sure this was good before proceeding.

**Comment by davharris** [comment]
Weird. I'm not getting those warnings. I'll keep poking at it. 

Dave

**Comment by ethanwhite** [comment]
Could they be from one of the datasets you didn't run? The ones not in
White et al. 2012?

**Comment by davharris** [comment]
That’s my best guess.  Do you want to see which dataset(s) are triggering the warnings, or should I?

**Comment by ethanwhite** [comment]
It will probably happen more quickly if you have a chance to look at it.

**Comment by davharris** [comment]
I just ran it on all the data sets I'm aware of (listed below) and found no warnings.

@ethanwhite can you see if you still get them?

`c("Actinopterygii", "Amphibia", "Arachnida", "bbs", "cbc", "Coleoptera", 
        "fia", "gentry", "mcdb", "naba", "Reptilia")`

**Comment by ethanwhite** [comment]
I'm still getting these on my home machine. Is there a package I might need to update?

```

**Comment by ethanwhite** [comment]
Of course if it's running fine on yours then you could also just run everything.

**Comment by davharris** [comment]
Maybe? I'm on R 3.2.4 using the following package versions:

magrittr_1.5     lme4_1.1-11      Matrix_1.2-4     tidyr_0.4.1.9000
ggplot2_2.1.0    dplyr_0.4.3.9001 progress_1.0.2

**Comment by ethanwhite** [comment]
I upgraded everything to the newest versions, except R which seems to be stuck at 3.2.3 in the Ubuntu repos. @rueuntal can you run this as well when you get the chance. That should tell us whether we can ignore my machine or figure out what's special about Dave's.

**Comment by ethanwhite** [comment]
@embaldridge if you haven't shared the Dropbox folder with @rueuntal yet could you go ahead and do so. Thanks.

**Comment by embaldridge** [comment]
I think I did; will check and fix if I didn't.

**Comment by embaldridge** [comment]
Fixed.  Shared with USU email, which is not very helpful at this point.

**Comment by rueuntal** [comment]
Git the link. Thanks @embaldridge .

>@rueuntal can you run this as well when you get the chance. That should tell us whether we can ignore my machine or figure out what's special about Dave's.
Happy to. Sorry to be a bit behind - which version/file should I run?

**Comment by ethanwhite** [comment]
You want to checkout this PR (if you want to do it directly from the main repo see: https://gist.github.com/piscisaureus/3342247), put the data from the `chapter1` folder in the Dropbox into the `sad-data` subdirectory in the repo, and then run:

```R
> source('sad-postprocess.R')
```

At least that's what I've been doing...

**Comment by ethanwhite** [comment]
And now worries about being a bit behind. We're all right there with you :smiley_cat:.

**Comment by rueuntal** [comment]
Thanks @ethanwhite !

I couldn't seem to find the _likelihood_results.csv files. Can someone upload them if they are not already in the folder?

**Comment by embaldridge** [comment]
@ethanwhite ?  All I have are *_likelihoods.csv

**Comment by ethanwhite** [comment]
I've added my copy of the `_likelihood_results.csv` files to the Dropbox.

To generate these files yourself you can run `sad-comparisons.py`, which could be worth doing in case my version of these files are the source of the remaining issues. To get it to run all of the datasets you'll need to add a `dataset_config.txt` file to the `sad-comparisons` directory with the following contents:

```
Actinopterygii
Amphibia
Arachnida
bbs
cbc
Coleoptera
fia
gentry
mcdb
naba
Reptilia
```

This does take a little while if I recall correctly. Probably a couple of hours. So I'd start with just running `sad-postprocess.R` and if it's still throwing warnings try rebuilding the `likelihood_results.csv` files.

**Comment by rueuntal** [comment]
Thanks @ethanwhite . I was rebuilding the `likelihood_results.csv` files, but had just gone through BBS when you uploaded them. 

Using your version of the files didn't throw any warnings on my machines.

**Comment by ethanwhite** [comment]
OK, great. Now I wish I'd suggesting you check that a month ago 😳.

Thanks for all of your hard work on this @davharris and thanks to everyone else for testing & feedback. In it goes!

**Pull request merged**
