### PR TITLE
add missing plot labels

### PR DESCRIPTION
**Pull request by davharris**
The Github page for the PR lets you see the changes in different ways via the options under the plot below.

### CODE REVIEW

**Comment by davharris** [comment]
Please don't tell the reproducibility police, but I used a Photoshop knock-off for this part.

**Comment by ethanwhite** [comment]
My initial reaction is to say that the labels should be up next to the x-axis, but there's no perfect solution here so I'm flexible.

**Comment by davharris** [comment]
I don't care one way or the other.  I'll change it if I have some spare time.

**Comment by ethanwhite** [comment]
I went ahead and merged and I'll submit a PR making this change shortly.

**Pull request merged**
